export const AUTH_USER_REQUEST = "AUTH_USER_REQUEST";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_FAIL = "AUTH_USER_FAIL";


export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGOUT_USER = "LOGOUT_USER";

export const POST_LIKE = "POST_LIKE";
export const POST_UNLIKE = "POST_UNLIKE";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";


export const ALL_USER_REQUEST = "ALL_USER_REQUEST"; 
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS"; 
export const ALL_USER_FAIL = "ALL_USER_FAIL"; 

export const USER_BIO_REQUEST = "USER_BIO_REQUEST"; 
export const USER_BIO_SUCCESS = "USER_BIO_SUCCESS"; 
export const USER_BIO_FAIL = "USER_BIO_FAIL"; 


export const UPDATE_BIO_REQUEST = "UPDATE_BIO_REQUEST"; 
export const UPDATE_BIO_SUCCESS = "UPDATE_BIO_SUCCESS"; 
export const UPDATE_BIO_FAIL = "UPDATE_BIO_FAIL"; 

export const FOLLOW_REQUEST = "FOLLOW_REQUEST";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const FOLLOW_FAIL = "FOLLOW_FAIL";

export const UNFOLLOW_REQUEST = "UNFOLLOW_REQUEST";
export const UNFOLLOW_SUCCESS = "UNFOLLOW_SUCCESS";
export const UNFOLLOW_FAIL = "UNFOLLOW_FAIL";

export const ADD_COMMENT = "ADD_COMMENT"

export const ALL_POST_REQUEST = "ALL_POST_REQUEST";
export const ALL_POST_SUCCESS = "ALL_POST_SUCCESS";
export const ALL_POST_FAIL = "ALL_POST_FAIL";

export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";
export const DELETE_POST = "DELETE_POST"


export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";